apiVersion: v1
kind: Service
metadata:
  name: my-emp1
  labels:
    run: my-emp1
spec:
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  type: NodePort
  selector:
    run: my-emp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-emp1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-emp1
  template:
    metadata:
      labels:
        run: my-emp1
    spec:
      containers:
        - name: my-emp1
          image: qasim313/nodejs-app
          ports:
            - containerPort: 8888
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
